.\"	$Id$
.\"
.\" Copyright (c) 2017 Scott Bennett
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: March 23 2017 $
.Dt PASSGEN 1
.Os
.Sh NAME
.Nm passgen
.Nd generate random passwords
.Sh SYNOPSIS
.Nm passgen
.Op Fl l Ar passlength
.Op Fl n Ar passnum
.Sh DESCRIPTION
The
.Nm
utility prints a number of random passwords up to 50 characters long.
.Pp
The options are as follows:
.Bl -tag -width itis-thirteen
.It Fl l Ar passlength
Length of the generated password. The default (and minimum) is 13.
.It Fl n Ar passnum
Number of passwords to generate, one per line.
.Nm
will only generate 1 password by default.
.El
.Sh EXAMPLE
.\"
.Sh EXIT STATUS
.Nm
exits 0 on success, and 1 if an error occurs.
.Sh AUTHORS
.Nm
was written by
.An Scott Bennett ,
.Mt scottb@fastmail.com .
.Sh CAVEATS
.Nm
will only compile on
.Ox
because it relies on
.Xr arc4random_uniform 3 ,
.Xr strtonum 3 , and
.Xr explicit_bzero 3 .
